###项目启动端口
server:
  port: 8088

###################  spring配置  ###################
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vert?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: admin123
    filters: log4j2,wall,mergeStat

logging:
  level.root: info
  level.com.zhaoyang.vert: debug
  path: logs/
  file: vert.log

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/zhaoyang/vert/**/mapping/*.xml
  typeAliasesPackage: com.zhaoyang.vert.module.system.model
  global-config:
    id-type: 0  #0:数据库 id 自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
